cmake_minimum_required(VERSION 3.16)
project(Operator_Overload_Lab LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
add_executable(bank_accounts main.cpp BankAccount.cpp)
enable_testing()
add_executable(account_tests tests/BankAccountTests.cpp BankAccount.cpp)
add_test(NAME BankAccountTests COMMAND account_tests)
